### ISSUE TITLE
clarification of details in function plx2mda()

### ISSUE THREAD

**Issue by happyqiu** [byronprice/MounSortPipeline#1]
In README text, it's said that first I should use plx2mda.m to transfer .plx raw data to .mda files. But it seems that another .mat file is generated already before running this code.  Could you please explain a bit more about generation (the format and contents) of the .mat file?

**Comment by byronprice** [comment]
I sort of just made this repo for our lab, so it’s not user friendly. But, inside the plx2mda.m function, I make a call to “readall.m”, which is essentially the same readall.m function as provided in the Plexon “Omniplex and MAP Offline SDK Bundle”. In Plexon’s version of readall.m, you enter the filename manually and then all of the variables are stored to the workspace. My version is modified to be a function that takes the .plx filename as input and outputs a .mat file of the same name with all of the variables stored. We’re saving threshold crossings timestamps rather the full broadband data, so everything in the code assumes that format. The most important things to be saved in the “readall.m” are “allts” and “allwaves”. “allts” is a cell array, usually 27x17 per Plexon’s formatting, that contains all of the timestamps for thresholding crossings on each of the electrodes. “allwaves” is the same size and contains all of the corresponding waveforms for each threshold crossing. The plx2mda.m code is doing a few things with the LFP data as well, stored in “allad”, but that part is not completed.

Hope that helps!

**Comment by happyqiu** [comment]
Thank you so much for the explanation!
